---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/appdata/sonarr:/config
      - /mnt/media:/media
      - /mnt/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/appdata/radarr:/config
      - /mnt/media:/media
      - /mnt/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/appdata/readarr:/config
      - /mnt/media:/media
      - /mnt/downloads:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/appdata/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  overseerr:
    image: sctx/overseerr
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    ports:
      - 5055:5055
    volumes:
      - /opt/appdata/overseerr:/app/config
    restart: unless-stopped
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/appdata/sabnzbd:/config
      - /mnt/downloads:/downloads
    ports:
      - 8080:8080
    restart: unless-stopped
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/appdata/homarr:/app/data/configs
    ports:
      - 7575:7575
    restart: unless-stopped
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - TZ=America/Chicago
      - WATCHTOWER_SCHEDULE=0 0 3 * * *
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=pushover://auuu5h8i6nq8ybfitcxcvgy9y4tpa8@unz3irft9xy83syphaofwhn8cx9zb2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
