---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/appdata/sonarr:/config
      - /mnt/media:/media
      - /mnt/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/appdata/radarr:/config
      - /mnt/media:/media
      - /mnt/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/appdata/readarr:/config
      - /mnt/media:/media
      - /mnt/downloads:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped
  speakarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: speakarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/appdata/speakarr:/config
      - /mnt/media:/media
      - /mnt/downloads:/downloads
    ports:
      - 8788:8787
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/appdata/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  overseerr:
    image: sctx/overseerr
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    ports:
      - 5055:5055
    volumes:
      - /opt/appdata/overseerr:/app/config
    restart: unless-stopped
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/appdata/sabnzbd:/config
      - /mnt/downloads:/downloads
    ports:
      - 8080:8080
    restart: unless-stopped
  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - SECRET_ENCRYPTION_KEY=49dde5c1039a6418a8cde7ef885e3600661b11e2de026d9a0ce0ca15dfabfeb8
    volumes:
      - /opt/appdata/homarr:/appdata
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 7575:7575
    restart: unless-stopped
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/appdata/tautulli:/config
    ports:
      - "8181:8181"
    restart: unless-stopped
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    ports:
      - "13378:80"
    volumes:
      - /opt/appdata/audiobookshelf/config:/config
      - /opt/appdata/audiobookshelf/metadata:/metadata
      - /mnt/media:/media
    restart: unless-stopped
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - TZ: America/Chicago
      - WATCHTOWER_SCHEDULE: "0 0 3 * * *"
      - WATCHTOWER_CLEANUP: "true"
      - WATCHTOWER_NOTIFICATIONS: shoutrrr
      - WATCHTOWER_NOTIFICATION_URL: pushover://shoutrrr:auuu5h8i6nq8ybfitcxcvgy9y4tpa8@unz3irft9xy83syphaofwhn8cx9zb2
      - WATCHTOWER_NOTIFICATION_TEMPLATE: '{{.Time}}: {{.ContainerName}} updated from {{.ImageOld}} to {{.ImageNew}} (ID: {{.ImageID}})'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  portainer-agent:
    image: portainer/agent:latest
    container_name: portainer-agent
    restart: unless-stopped
    environment:
      - AGENT_CLUSTER_ADDR=tasks.portainer-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - "9001:9001"
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    privileged: true
    ports:
      - "9292:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg:/dev/kmsg
    restart: unless-stopped
